### ISSUE TITLE
Nil pointer evaluating interface {}.region

### ISSUE THREAD

**Issue by kennith** [hashicorp/nomad-pack#179]
In my template,

```
[[ template "region" . ]]
```

when I run nomad-pack run ., it returns with the message

`nil pointer evaluating interface {}.region`

This is how it looks in my _region.tpl,

```
[[- define "region" -]]
[[- if not (eq .gitlab_runner.region "") -]]
    region = [[ .gitlab_runner.region | quote]]
[[- end -]]
[[- end -]]
```

The repo that I am getting the error is here: https://github.com/builtbyeleven/gitlab-runner-nomad-pack/tree/main/packs/gitlab_runner

Reference: Originally discussed at https://discuss.hashicorp.com/t/nil-pointer-evaluating-interface-region/32973

**Comment by angrycub** [comment]
In reviewing your pack, I noticed the root cause of your issue.  In the metadata.hcl file, the pack is named `gitlab-runner`, but in the templates, it is referred to `gitlab_runner`.  The `variables.hcl` file is read into a map using the pack name as defined in that file. I'm not sure if there is a way to improve the error message here since we are deep in go template at this point, but I will look into that.
