### ISSUE TITLE
Unable to edit JobSpec in Nomad UI after Nomad Pack Deployment

### ISSUE THREAD

**Issue by bernardoVale** [hashicorp/nomad-pack#425]
### Steps to Reproduce

1. Deploy any nomad pack job with Nomad 1.6 and `nomad-pack` [main branch](https://github.com/hashicorp/nomad-pack/commit/a94eb6df12bd6e0e5a9ebaf7849e3347a4e8f7ba)
2. Edit anything in the UI, you will see that nomad plan drops all `pack.*` meta attributes
3. Try to deploy again with nomad-pack

Deploy fails with error `Error: job with id "some-job" already exists and is not managed by nomad pack`

Inspecting the code, it seems that the problem is that we save the [rendered template](https://github.com/hashicorp/nomad-pack/blob/main/internal/runner/job/job.go#L119) without the extra injected pack meta attributes.

**Comment by bernardoVale** [comment]
@philrenaud I don't think it's a Nomad UI problem. The UI behavior is correct. If you update the raw JSON (Full Definition) it won't drop the meta. It only breaks if you edit the HCL content (Job Spec).

Worth also defining what break means in this context. Nomad UI will deploy the changes fine, but since it removes nomad pack meta attributes, nomad-pack will refuse to redeploy.

**Comment by philrenaud** [comment]
Thanks @bernardoVale — just tagged it so I could try to to reproduce, but you're probably right. We've done a few pack-quality-of-life related changes in the UI recently so just wanted to see if there was an opportunity to expand on it here.

**Comment by angrycub** [comment]
@bernardoVale, to close the circle on this issue. Nomad-pack parses the rendered pack templates into Nomad jobspecs using the jobspec/jobspec2 libraries. As you noted, the pack metadata is preserved when you round trip the JSON, but not the HCL. This is an interesting issue since the HCL is designed to be user-facing (and consequently is harder to machine manage) but also in this case that meta is non-user provided; so if we were to inject it into the HCL it could confuse users that aren't aware of pack's deploy semantics.

I'm going to circle up with @philrenaud and see if there's a good way to thread this needle generally, since anyone using the API package can do the same sort of thing that Pack does with regard to making the [`submission`](https://developer.hashicorp.com/nomad/api-docs/jobs#read-job-submission) not strictly match the submitted JSON spec.  Meta is the most likely block to be manipulated post-processing, like pack does, but there can be other cases too.

**Comment by bernardoVale** [comment]
why this issue is closed? How did it get fixed?

**Comment by angrycub** [comment]
You will need to edit pack jobs in the UI using the JSON job editor until the UI supports maintaining the pack metadata.  There is nothing to be done on the Pack side of things.
