### ISSUE TITLE
Nomad Pack - Tech Preview Feedback

### ISSUE THREAD

**Issue by jrasell** [hashicorp/nomad-pack#72]
Thank you for trying Nomad Pack during this technical preview release. We are really keen to hear any and all feedback related to the Nomad Pack application, Nomad Pack Registries, and Nomad packs. This issue is designed to track general feedback from the community that will help drive design changes as we move towards a beta release. When providing feedback, including any use cases and requirements will be hugely beneficial.

If you have found a bug please raise this as a separate issue against the repository so that we can track this independently. Please also use the [Nomad Discuss forum](https://discuss.hashicorp.com/c/nomad/28) for general usage questions.

Thanks from the Nomad Team!

**Comment by apollo13** [comment]
@arianvp 
> Text based templates is helm's largest design mistake as it's so error prone and is actually why I use terraform to deploy my Kubernetes projects instead of helm.

I fully agree with you there (not a hashicorp member) and would love to see if we could get away without a new template engine by maybe instead extending HCLs capabilities. As far as I understand it though, there are a few things you cannot express in HCL. For instance could one have an `service {}` stanza that is added to the job file based on a boolean variable? If not, that might be the reason to support more templating functionality -- not sure if it is good to have jobs that dynamic, but that is what people are used to I guess… Also looking at https://github.com/hashicorp/nomad-pack-community-registry/blob/main/packs/traefik/templates/_helpers.tpl -- that might be hard to express in HCL?

**Comment by kds-rune** [comment]
> Also by default the hashicorp/nomad-pack:0.0.1-techpreview1 image is broken. I had to do this to get it to run: FROM hashicorp/nomad-pack:0.0.1-techpreview1 USER root RUN apk update && apk add git USER nomad-pack
> 
> As without git installed nomad-pack registry list would fail, like so: go-getter URL is github.com/hashicorp/nomad-pack-community-registry ! Could Not Install Registry
> 
Encountered this issue as well, and I initially just downloaded the binary in my pipeline instead (since the runner has git pre-installed). I've now also created a separate nomad-pack build on [docker-hub](https://hub.docker.com/repository/docker/kdsda/nomad-pack), since I was not able to locate the Dockerfile/build in the official repo..

**Comment by k0wl0n** [comment]
it would be nice if we can parse datacenter into variable.
ive got some error here, because my DC is not dc1.

`app 2 unplaced
No nodes were eligible for evaluation
No nodes are available in datacenter dc1`

something like
`nomad-pack run hello_world --var message=hola --datacenter=<whatever>`

**Comment by kds-rune** [comment]
You can already do this with the following format:
```bash
nomad-pack render hello_world --var message=hola --var datacenters="[\"dc2\",\"dc3\"]"
```

**Comment by kds-rune** [comment]
> it would be nice if we can parse datacenter into variable. ive got some error here, because my DC is not dc1.
> 
> `app 2 unplaced No nodes were eligible for evaluation No nodes are available in datacenter dc1`
> 
> something like `nomad-pack run hello_world --var message=hola --datacenter=<whatever>`

You can use the following format:
```bash
nomad-pack run hello_world --var message=hola --datacenters="[\"dc1\"]"
```

**Comment by gregory112** [comment]
I have been writing a lot of packs now for quite some time and I must say I have feedback/questions about a few things:

1. `fileContents` function only looks at local folder where `nomad-pack` is executed, as opposed to `template` function
2. To create a list that is configurable, like a list of DNS servers perhaps, naturally I have to create a `list(string)` variable in the variables file. I have to use `mustToJson` function to convert the list into a syntax that is HCL2 compliant. Maybe a documentation or example or even easier/cleaner alternative should exist as modifying things like datacenters or DNS servers is crucial to make portable Nomad packs
3. I wonder if we can make Nomad volumes via nomad-pack too? I think there is already a feature request for this
4. I wonder if it can also be configured to create Vault secrets/policies too? My concern is that in a pack we think about everything in that pack as a single entity. It is difficult to document that a pack requires some additional setups to be able to work, for example if a pack requires that "db_username" secret field to exist in some Vault secret path to configure username, maybe Nomad pack should be able to facilitate this so secrets can now be maintained as codes, be overridden through for example environment variables, and so on. Previously, there is no standardized way to manage secrets other than by reading the Nomad jobs
5. Maybe deprecate `levant` because nomad-pack is a superset of levant? I used to use levant too.

Thank you for the good work.

**Comment by const-tmp** [comment]
Basically it's not working at all https://github.com/hashicorp/nomad-pack/issues/417

**Comment by jrasell** [comment]
Closing this issue out and we will convert feedback items into individual tickets, thanks everyone.
